const data = [
    "Soyez un ami généreux et un ennemi loyal",
    "Ne jamais abandonner!",
    "Les vieux amis, les vieux vins et le vieil or sont les meilleurs",
    "Si vos désirs ne sont pas extravagants, ils seront exaucés",
    "Chaque ami se réjouit de votre succès",
    "Vous devriez pouvoir entreprendre et compléter n'importe quoi",
    "Vous jouirez d'une bonne santé, vous serez entouré de luxe",
    "Vous êtes une personne de fort sens du devoir",
    "Rêvez de grands rêves, et comme vous rêvez, vous deviendrez.",
    "Vous avez une nature calme et discrète.",
    "Les grandes pensées viennent du cœur.",
    "Tu aimes la paix",
    "Juge pas selon l'apparence.",
    "Celui qui vous admire grandement est caché sous vos yeux.",
    "Voyager plus souvent est important pour votre santé et votre bonheur.",
    "Vous partagerez de bonnes nouvelles avec toutes les personnes que vous aimez",
    "Vous avez la réputation d'être franc et honnête.",
    "Vous êtes toujours le bienvenu dans n'importe quel rassemblement.",
    "Vous voyagerez et vous ferez fortune.",
    "Ouvre ton cœur - il peut toujours être refermé.",
    "Etre heureux, ce n'est pas toujours être parfait.",
    "La prochaine fois que vous en aurez l'occasion, allez en montagnes russes.",
    "Essayez tout une fois, même les choses que vous ne pensez pas aimer.",
    "La vie est trop courte pour garder rancune.",
    "Rêvez votre rêve et votre rêve rêvera de vous.",
    "Être seul et être seul sont deux choses différentes.",
    "Ne vous inquiétez pas pour les choses du passé, vous ne pouvez rien y faire pour le moment. Ne vous inquiétez pas pour les choses qui se passent maintenant, tirez le meilleur parti d'une mauvaise situation. Ne vous inquiétez pas pour les choses à venir, ils peuvent ne jamais arriver. ",
    "Demain, prenez un moment pour faire quelque chose juste pour vous.",
    "Quelqu'un près de vous attend que vous appeliez.",
    "Un biscuit de fortune virtuel ne satisfera pas votre faim comme celle d'un biscuit fait maison.",
    "Sourire. Demain est un autre jour.",
    "Vous ne pouvez jamais être certain du succès, mais vous pouvez être certain de l'échec si vous n'essayez jamais.",
    "Il faut dix fois plus de muscles pour froncer les sourcils que pour sourire.",
    "Tirez pour la lune! Si vous manquez, vous serez toujours parmi les étoiles.",
    "Gardez les yeux ouverts. Vous ne savez jamais ce que vous pourriez voir.",
    "Dites-leur ce que vous pensez vraiment. Sinon, rien ne changera.",
    "Laissez votre coeur prendre vos décisions - il ne sera pas aussi confus que votre tête.",
    "Travailler dur vous fera vivre une vie heureuse.",
    "Une bonne surprise vous attend.",
    "Aujourd’hui, c’est à vous de créer le calme que vous aspirez.",
    "Un ami ne demande que votre temps, pas votre argent.",
    "Si vous refusez d'accepter autre chose que le meilleur, vous l'obtenez très souvent.",
    "Un sourire est votre passeport dans le cœur des autres.",
    "Un bon moyen de rester en bonne santé est de manger plus de nourriture chinoise.",
    "Vos principes élevés sont synonymes de succès.",
    "Le travail acharné porte ses fruits dans le futur, la paresse en vaut la peine maintenant.",
    "Le changement peut faire mal, mais il ouvre la voie à quelque chose de mieux.",
    "Profitez de la chance qu'un compagnon vous apporte.",
    "Les gens sont naturellement attirés par vous.",
    "Caché dans une vallée au bord d'un ruisseau, ce sera le type d'endroit où vous trouverez votre rêve.",
    "Une rencontre fortuite ouvre de nouvelles portes au succès et à l'amitié.",
    "Vous apprenez de vos erreurs ... Vous apprendrez beaucoup aujourd'hui.",
    "Si vous avez quelque chose de bien dans votre vie, ne le laissez pas partir!",
    "Quel que soit ton but dans la vie, embrasse-le, visualise-le, et ce sera le tien.",
    "Vos chaussures vont vous rendre heureux aujourd'hui.",
    "Vous ne pouvez pas aimer la vie tant que vous ne menez pas la vie que vous aimez",
    "Soyez à l'affût des événements à venir; ils jettent leurs ombres à l'avance.",
    "La terre est toujours dans l'esprit d'un oiseau qui vole.",
    "L’homme ou la femme que vous désirez a le même sentiment que vous.",
    "Bien affronter l'adversité est la source de votre force.",
    "Un rêve que vous avez deviendra réalité.",
    "Nos actes nous déterminent, autant que nous déterminons nos actes.",
    "Ne jamais abandonner. Tu n'es pas un échec si tu n'abandonnes pas.",
    "Vous deviendrez grand si vous croyez en vous-même.",
    "Il n'y a pas de plus grand plaisir que de voir prospérer ses proches.",
    "Vous allez épouser votre amoureux.",
    "Une personne très attrayante a un message pour vous.",
    "Vous connaissez déjà la réponse aux questions qui vous trottent dans la tête.",
    "C’est maintenant, et dans ce monde, que nous devons vivre.",
    "Vous devez essayer, ou vous détester pour ne pas essayer.",
    "Vous pouvez faire votre propre bonheur.",
    "Le plus grand risque est de ne pas en prendre un.",
    "L'amour de votre vie entre dans votre planète cet été.",
    "L'amour peut durer toute une vie, si vous le souhaitez.",
    "L'adversité est le parent de la vertu.",
    "Un problème grave vous contournera.",
    "Un petit inconnu entrera bientôt dans votre vie avec des bénédictions à partager.",
    "Le moment est venu d'essayer quelque chose de nouveau.",
    "La richesse vous attend très bientôt.",
    "Si vous sentez que vous avez raison, tenez fermement à vos convictions.",
    "Si l'hiver arrive, le printemps peut-il être loin derrière?",
    "Gardez votre œil sur quelqu'un de spécial.",
    "Vous avez beaucoup de talent à bien des égards.",
    "Un étranger, est un ami que vous n'avez pas encore parlé.",
    "Un nouveau voyage remplira votre vie de souvenirs indicibles.",
    "Vous allez voyager dans de nombreux endroits exotiques de votre vie.",
    "Votre capacité d'accomplissement suivra avec succès.",
    "Rien n’étonne autant les hommes que le bon sens et la simplicité.",
    "C'est incroyable à quel point vous pouvez faire du bien si vous ne vous souciez pas de qui obtiendra le crédit.",
    "Tout le monde est d'accord. Tu es le meilleur.",
    "LA VIE NE CONSISTE PAS À PORTER DE BONNES CARTES, MAIS À JOUER CEUX QUE VOUS TENEZ BIEN.",
    "La jalousie n'ouvre pas les portes, elle les ferme!",
    "Il vaut mieux être seul parfois.",
    "Quand la peur vous blesse, vaincre et vaincre!",
    "Laissez les actes parler.",
    "Vous serez appelé à remplir une position de grand honneur et de responsabilité.",
    "L'homme au sommet de la montagne n'est pas tombé là-bas.",
    "Vous allez vaincre les obstacles pour réussir.",
    "Les joies sont souvent les ombres, jetées par les chagrins.",
    "La fortune sourit aux audacieux.",
    "Un mouvement ascendant initié dans le temps peut contrecarrer le destin.",
    "Un voyage de mille kilomètres commence par un seul pas.",
    "Parfois, il suffit de se coucher par terre.",
    "N'abandonnez jamais. Trouvez toujours une raison pour continuer d'essayer.",
    "Si vous avez quelque chose qui vaut la peine de vous battre, alors battez-vous pour cela.",
    "Arrête de souhaiter. Commence à faire.",
    "Acceptez votre passé sans regret. Traitez votre présent avec confiance. Faites face à votre avenir sans crainte.",
    "Restez fidèle à ceux qui feraient la même chose pour vous.",
    "Demandez-vous si ce que vous faites aujourd'hui vous rapproche de l'endroit où vous souhaitez être demain.",
    "Le bonheur est une activité.",
    "L'aide est toujours nécessaire mais pas toujours appréciée. Restez fidèle à votre cœur et aidez les plus démunis, qu'ils l'apprécient ou non.",
    "Affûtez votre instinct de compétition.",
    "Terminez votre travail sous la main ne soyez pas gourmand.",
    "Pour réussir aujourd'hui, regardez d'abord pour vous-même.",
    "Votre fortune est aussi douce qu'un biscuit.",
    "L'intégrité est l'essence de tout succès.",
    "Si vous êtes heureux, vous réussissez.",
    "Vous serez toujours entourés de vrais amis",
    "Le fait de croire que vous êtes belle vous fera paraître belle aux autres autour de vous.",
    "Happinees vient d'une bonne vie.",
    "Avant d'essayer de plaire aux autres, pensez à ce qui vous rend heureux.",
    "Si vous avez faim, commandez plus de nourriture chinoise.",
    "Votre opportunité en or arrive bientôt.",
    "Car la haine n'est jamais vaincue par la haine. La haine est vaincue par l'amour.",
    "Vous ferez beaucoup de changements avant de vous installer joyeusement.",
    "Un homme est né pour vivre et ne pas se préparer à vivre.",
    "Vous ne pouvez devenir riche qu'en enrichissant les autres.",
    "Ne cherchez pas le bonheur, créez-le.",
    "Vous allez réussir en amour.",
    "Tous vos doigts ne peuvent pas être de la même longueur.",
    "Les paroles sages tombent souvent sur un terrain aride, mais un mot gentil n'est jamais jeté.",
    "Une vie de bonheur vous attend.",
    "Il est très possible que vous atteigniez la grandeur dans votre vie.",
    "Faites preuve de tact; négligez votre propre opportunité.",
    "Vous êtes le contrôleur de votre destin.",
    "Tout se passe pour une résonance.",
    "Comment pouvez-vous avoir une belle fin sans faire de belles erreurs.",
    "Vous pouvez ouvrir les portes avec votre charme et votre patience.",
    "Bienvenue au changement qui entre dans votre vie.",
    "Il y aura bientôt une bonne romance pour vous.",
    "Votre rêve le plus cher deviendra réalité d'ici cette année.",
    "Vous avez un intérêt profond pour tout ce qui est artistique.",
    "Votre nature émotionnelle est forte et sensible.",
    "Une lettre d'une grande importance peut vous parvenir d'un jour à l'autre.",
    "Une bonne santé sera à vous pendant longtemps.",
    "Vous allez mieux connaître un collègue.",
    "Pour être vieux et sage, vous devez d’abord être jeune et stupide.",
    "L’échec n’est que l’opportunité de recommencer plus intelligemment",
    "L'intégrité fait ce qu'il faut, même si personne ne nous regarde.",
    "Conquérez vos peurs ou ils vous conquerront.",
    "Vous êtes un amoureux des mots; un jour, vous écrirez un livre.",
    "Dans cette vie, ce n'est pas ce que nous prenons, mais ce que nous abandonnons qui nous rend riches.",
    "La peur peut nous empêcher de dormir toute la nuit, mais la foi fait un beau coussin.",
    "Cherchez la signification de votre problème en ce moment. Essayez de comprendre.",
    "Ne contrariez jamais le conducteur de la voiture dans laquelle vous êtes; ils maîtrisent votre destin jusqu'à votre retour à la maison.",
    "Celui qui glisse sur le sol n'est pas toujours un ennemi.",
    "Vous apprenez de vos erreurs, vous apprendrez beaucoup aujourd'hui.",
    "Vous n'avez qu'à vous inspirer de votre propre reflet. Parce que vous êtes belle!",
    "Vous n'êtes pas jugé par vos efforts, vous êtes jugé sur vos performances.",
    "Les rivières ont besoin de sources.",
    "Les bonnes nouvelles de loin peuvent vous apporter un visiteur de bienvenue.",
    "Quand tout le reste semble échouer, souriez pour aujourd'hui et aimez tout simplement quelqu'un.",
    "La patience est une vertu, à moins que ce ne soit contre un mur de briques.",
    "Lorsque vous regardez en bas, tout ce que vous voyez est de la saleté, alors continuez à regarder en l'air.",
    "Si vous avez peur de secouer les dés, vous ne lancerez jamais un six.",
    "Même si la personne qui semble avoir le plus tort, a aussi souvent raison.",
    "Une seule conversation avec un homme sage vaut mieux que dix ans d'études.",
    "Le bonheur est souvent le fruit d'un travail acharné.",
    "Le monde est peut-être votre huître, mais cela ne veut pas dire que vous aurez sa perle.",
    "Votre vie sera remplie de moments magiques.",
    "Votre véritable amour se montrera à vous au clair de lune.",
    "Ne suivez pas où le chemin peut mener. Allez où il n'y a pas de chemin ... et laissez un sentier",
    "Ne craignez pas ce que vous ne savez pas",
    "L'objet de votre désir se rapproche.",
    "Vous avez le flair d'ajouter une dimension fantaisiste à toute histoire.",
    "Si vous souhaitez connaître l'esprit d'un homme, écoutez ses paroles",
    "L'énergie la plus inutile est d'essayer de changer quoi et qui Dieu a si soigneusement créé.",
    "Ne soyez pas couverts de tristesse et ne vous laissez pas berner par le bonheur, ils doivent exister tous les deux",
    "Vous aurez une bonne chance inattendue.",
    "Vous aurez une bonne surprise",
    "Tous les progrès ont lieu parce que les gens osent être différents.",
    "Votre capacité d'accomplissement sera suivie par le succès.",
    "Le monde est toujours prêt à recevoir des talents à bras ouverts.",
    "Les choses peuvent arriver à ceux qui attendent, mais seulement les choses laissées par ceux qui bousculent.",
    "Nous ne pouvons pas aider tout le monde. Mais tout le monde peut aider quelqu'un.",
    "Chaque jour est un nouveau jour. Mais demain n'est jamais promis.",
    "Exprimez-vous: ne vous retenez pas!",
    "Il n'est pas nécessaire de montrer aux autres que vous avez du changement; le changement sera évident.",
    "Vous avez une profonde connaissance des arts et de la musique.",
    "Si vos désirs ne sont pas extravagants, ils seront récompensés.",
    "Vous essayez de ne jamais échouer. Vous ne devez jamais gagner.",
    "Ne jamais abandonner quelqu'un à qui on ne passe pas une journée sans y penser.",
    "Il n'est jamais rentable de donner un coup de pied à une mouffette.",
    "En cas d’incendie, restez calme, payez votre facture et courez.",
    "La prochaine pleine lune apporte une soirée enchanteresse.",
    "Tous les yeux fermés ne dorment pas, ni les yeux ouverts ne voient.",
    "Impossible est un mot qui ne se trouve que dans le dictionnaire des fous.",
    "Vous allez bientôt assister à un miracle.",
    "Il est toujours temps de faire ce qui est juste.",
    "L'amour est aussi nécessaire pour l'homme que la nourriture et le logement.",
    "Vous allez faire tourner les têtes.",
    "Vous êtes extrêmement aimé. Ne vous inquiétez pas :)",
    "Si vous n'êtes jamais patient, vous ne réussirez jamais à rien. Si vous croyez pouvoir le faire, vous serez récompensé du succès.",
    "Vous allez bientôt vous lancer dans une entreprise.",
    "Vous croyez en la bonté des hommes.",
    "Vous aurez une vie longue et riche.",
    "Vous ferez un agréable voyage dans un lieu éloigné.",
    "Vous êtes une personne de culture.",
    "Gardez les choses simples. Plus vous en dites, moins les gens s'en souviennent.",
    "La vie est comme une équipe de chiens de traîneau. Si vous n'êtes pas le chien de tête, le paysage ne change jamais.",
    "La prospérité fait des amis et l'adversité les tente.",
    "Rien ne vous semble impossible.",
    "La patience est amère, mais le fruit est doux.",
    "La seule certitude est que rien n’est certain.",
    "Le succès est la somme de mes visions uniques réalisées par la sueur de la persévérance.",
    "Lorsque vous vous attendez à ce que votre adversaire cède, vous devriez également éviter de le blesser.",
    "L'intelligence est la porte de la liberté et l'attention alerte est la mère de l'intelligence.",
    "Reculer des individus qui sont impulsifs.",
    "Vous avez apprécié le repas? Achetez-en un pour y aller aussi.",
    "Vous croyez en la bonté de l'humanité.",
    "Une grande fortune s'abattra sur vous cette année.",
    "Maintenant, ces trois restent, la foi, l'espoir et l'amour. Le plus important d'entre eux est l'amour.",
    "Pour réussir aujourd'hui, regardez d'abord pour vous-même.",
    "La détermination est le réveil de la volonté humaine.",
    "Il n'y a pas de limites à l'esprit sauf celles que nous connaissons.",
    "Un coeur joyeux fait du bien comme un médicament.",
    "Dans la mesure du possible, restez simple.",
    "Votre souhait le plus cher deviendra réalité.",
    "La pauvreté n'est pas une honte.",
    "Si vous ne le faites pas très bien, ne le faites pas du tout.",
    "Vous avez un équipement inhabituel pour réussir, utilisez-le correctement.",
    "L'émotion est l'énergie en mouvement.",
    "Vous serez bientôt honoré par quelqu'un que vous respectez.",
    "La ponctualité est la politesse des rois et le devoir du peuple doux partout.",
    "Votre bonheur est intimement lié à votre vision de la vie.",
    "Les environs élégants seront bientôt à vous.",
    "Votre sourire apporte le bonheur à tous ceux que vous rencontrez.",
    "Au lieu de vous inquiéter et de vous angoisser, avancez de manière constructive.",
    "Croyez-vous? L'endurance et la persévérance seront récompensées.",
    "Une nouvelle entreprise est à l'horizon.",
    "Ne sous-estimez jamais le pouvoir du toucher humain",
    "Conservez le passé, mais finalement, laissez le temps aller et gardez les souvenirs dans le présent.",
    "La vérité est un sujet impopulaire. Parce qu'il est incontestablement correct.",
    "La chose la plus importante dans la communication est d’entendre ce qui n’est pas dit.",
    "Vous êtes large d'esprit et socialement actif.",
    "Ton plus cher rêve se réalise. Dieu veille particulièrement sur toi.",
    "Vous recevrez un grand prix ou un prix.",
    "Vos points d'interrogation actuels vont réussir.",
    "Vous avez une belle capacité à jouir de la vie.",
    "Vous allez vivre longtemps et profiter de la vie.",
    "Un admirateur cache son affection pour vous.",
    "Un souhait est ce qui fait que la vie se passe quand vous rêvez de pétales de roses.",
    "L'amour peut transformer un chalet en palais d'or.",
    "Prête ton argent et perds ton amour.",
    "Vous allez embrasser votre béguin ohhh lalahh",
    "Vous serez récompensé d'être un bon auditeur la semaine prochaine.",
    "Si vous n'abandonnez jamais l'amour, il ne vous abandonnera jamais.",
    "Libérez votre force de vie.",
    "Votre souhait sera exaucé.",
    "Il y a une perspective d'un temps passionnant pour vous.",
    "Aucune distance n'est trop grande, si deux cœurs sont liés l'un à l'autre.",
    "La terre est toujours dans l'esprit des oiseaux qui volent.",
    "Essayez? Non! Faites ou ne faites pas, vous ne pouvez pas essayer.",
    "Ne vous inquiétez pas, vous aurez une grande paix.",
    "Il est temps que vous demandiez à quelqu'un de spécial une date.",
    "Vous créez votre propre scène ... le public attend.",
    "Il n'est jamais trop tard. Tout comme il n'est jamais trop tôt.",
    "Découvrez le pouvoir en vous-même.",
    "Les bonnes choses prennent du temps.",
    "Arrêtez de penser à la route qui n'a pas été empruntée et ouvrez celle que vous avez faite.",
    "Mettez votre malheur de côté. La vie est belle, soyez heureux.",
    "Vous pouvez toujours aimer ce que vous ne pouvez pas avoir dans la vie.",
    "Faites un choix judicieux tous les jours.",
    "La circonstance ne fait pas l'homme; elle se le révèle.",
    "L'homme qui attend jusqu'à demain manque les opportunités d'aujourd'hui",
    "La vie ne s'améliore pas avec le hasard. Elle s'améliore avec le changement.",
    "Si vous n'attendez jamais rien, vous ne pourrez jamais être déçu.",
    "Les gens autour de vous seront plus coopératifs que d'habitude.",
    "La vraie sagesse se trouve dans le bonheur.",
    "On regrette toujours ce qui aurait pu être fait. Rappelez-vous pour la prochaine fois.",
    "Suivez votre bonheur et l'Univers ouvrira des portes là où il n'y avait que des murs.",
    "Trouvez un endroit paisible où vous pouvez faire des projets pour l'avenir.",
    "Toute l'eau du monde ne peut couler un navire que s'il pénètre à l'intérieur.",
    "La Terre est une école à apprendre.",
    "En musique, il faut penser avec son cœur et ressentir avec son cerveau.",
    "Si vous parlez honnêtement, tout le monde va écouter.",
    "Ganerosity se remboursera plus tôt que vous ne l'imaginez.",
    "les bonnes choses prennent du temps",
    "Fais ce qui est juste, pas ce que tu devrais.",
    "Réaliser la qualité de la journée n'est pas un mince exploit.",
    "La simplicité et la clarté devraient être le thème de votre robe.",
    "Les vertueux trouvent la joie tandis que les injustes trouvent le chagrin dans leurs actions.",
    "Tous les yeux fermés ne dorment pas, ni les yeux ouverts ne voient.",
    "Le pain aujourd'hui est meilleur que le gâteau demain.",
    "Dans tout, il y a un morceau de vérité. Mais un morceau.",
    "Un sentiment est une idée avec des racines.",
    "L'homme est né pour vivre et ne pas se préparer à vivre",
    "C'est bien d'avoir des papillons dans l'estomac. Faites-les voler en formation.",
    "Si vous ne donnez rien, vous n’obtiendrez rien",
    "Plus vous essayez de ne pas ressembler à vos parents, plus vous risquez de les devenir",
    "Un jour, tout sera parfaitement logique",
    "vous penserez par vous-même quand vous cesserez de laisser les autres penser pour vous",
    "Tout ira bien. Ne soyez pas obsédé. Le temps prouvera que vous avez raison, vous devez rester où vous êtes.",
    "Finissons-en maintenant, quelqu'un vous attend là-dessus",
    "Les meilleurs hommes, comme les meilleurs aciers, ont été trempés dans le four le plus chaud.",
    "Vous réalisez un rêve",
    "Le pire des amis peut devenir le meilleur des ennemis, mais vous allez toujours vous accrocher.",
    "Je pense que vous avez mangé votre fortune pendant que vous mangiez votre biscuit",
    "Si tu aimes quelqu'un, continue de te battre pour eux",
    "Fais ce que tu veux, quand tu veux, et tu seras récompensé",
    "Laissez vos fantasmes se détendre ...",
    "Le plus cool que tu penses être le plus bête que tu cherches",
    "Attendez-vous à de grandes choses et de grandes choses vont venir",
    "La roue de la bonne fortune tourne enfin dans votre direction!",
    "Ne menez pas si vous ne menez pas.",
    "Vous aurez toujours du succès dans votre carrière professionnelle",
    "Partagez votre bonheur avec les autres aujourd'hui.",
    "C'est à vous de nettoyer.",
    "Votre avenir sera heureux et productif.",
    "Saisissez chaque seconde de votre vie et savourez-la.",
    "Ceux qui marchent dans les traces des autres ne laissent pas de traces.",
    "L'échec est la mère de tous les succès.",
    "La difficulté au début signifie généralement la facilité à la fin.",
    "Ne cherchez pas trop à trouver la réponse mais à mieux comprendre la question.",
    "Votre façon de faire ce que font les autres est ce qui vous rend spécial.",
    "Une belle, intelligente et aimante personne viendra dans votre vie.",
    "L'amitié est un océan que vous ne pouvez pas voir en bas.",
    "Votre vie ne s'améliore pas par hasard, elle s'améliore par le changement.",
    "Notre devoir, en tant qu'hommes et femmes, est de procéder comme si aucune limite à notre capacité n'existait.",
    "Une expérience agréable est à venir: ne passez pas à côté.",
    "Notre perception et notre attitude à l'égard de toute situation détermineront l'issue",
    "Ils disent que vous êtes têtus; vous appelez cela de la persistance.",
    "Deux petits sauts valent parfois mieux qu'un grand saut.",
    "Une nouvelle garde-robe apporte une grande joie et un changement dans votre vie.",
    "Le remède contre le chagrin est le mouvement.",
    "C'est une bonne chose que la vie ne soit pas aussi sérieuse qu'elle le semble pour le serveur",
    "J'entends et j'oublie. Je vois et je me souviens. Je comprends et je comprends.",
    "J'ai un rêve ... Il est temps d'aller se coucher.",
    "Les idées que vous croyez absurdes mènent finalement au succès!",
    "Un être humain est un être décisif.",
    "Aujourd'hui est le moment idéal pour arroser votre jardin.",
    "Certains hommes rêvent de fortunes, d'autres rêvent de biscuits.",
    "Les choses ne sont jamais tout à fait comme elles semblent.",
    "le projet sur votre esprit va bientôt prendre de l'ampleur",
    "VOS ECHECS VOUS CONDUIRONT DE VOTRE SUCCÈS",
    "POUR OBTENIR LE RAINBOW, VOUS DEVEZ ASSURER LA PLUIE.",
    "La beauté est tout simplement la beauté. L'originalité est magique.",
    "Votre rêve se réalisera quand vous vous y attendrez le moins.",
    "Ne laissez pas votre main être étendue pour recevoir et fermez quand vous devriez rembourser.",
    "Ne vous inquiétez pas, la moitié des personnes que vous connaissez sont en dessous de la moyenne.",
    "La vision est l'art de voir ce qui est invisible pour les autres.",
    "Vous n'avez pas besoin de talent pour acquérir de l'expérience.",
    "Un esprit concentré est l'une des forces les plus puissantes de l'univers.",
    "Aujourd'hui, tu as versé ta dernière larme. Demain, la fortune frappe à ta porte.",
    "Soyez patient! La Grande Muraille ne s'est pas construite en un jour.",
    "Pense que tu peux. Pense que tu ne peux pas. De toute façon, tu auras raison.",
    "La sagesse est en route pour vous.",
    "Les circuits numériques sont fabriqués à partir de pièces analogiques.",
    "Si vous mangez une boîte de biscuits de fortune, tout est possible.",
    "Le meilleur est à venir.",
    "Je suis d'accord.",
    "Soyez direct, généralement on peut accomplir plus de cette façon.",
    "Un seul travail gentil tiendra au chaud pendant des années.",
    "Demandez à un ami de vous rejoindre lors de votre prochain voyage.",
    "Nous croyons en Dieu.",
    "L'amour est gratuit. La luxure vous coûtera tout ce que vous avez.",
    "Arrêtez de chercher pour toujours, le bonheur est juste à côté de vous.",
    "Vous n'avez pas besoin de réponses à toutes les questions de la vie. Demandez à votre père quoi faire.",
    "La jalousie est une émotion inutile.",
    "Vous n'êtes pas un fantôme.",
    "Il y a quelqu'un dans ta vie qui t'ennuie plutôt que tu dois écouter.",
    "Vous planterez la plus petite graine et celle-ci deviendra le plus grand et le plus puissant arbre du monde.",
    "Le rêve que vous rêvez toute votre vie n'en vaut pas la peine. Trouvez un nouveau rêve et, une fois que vous êtes certain de l'avoir trouvé, battez-vous pour l'avoir.",
    "Voyez si vous pouvez apprendre quelque chose des enfants.",
    "Il n'est jamais trop tard pour que de bonnes choses se produisent!",
    "Une conscience claire est généralement le signe d'un mauvais souvenir.",
    "Vise haut, le temps passe vite.",
    "On ne dort pas, cela ne signifie pas qu’ils sont réveillés.",
    "Un grand plaisir dans la vie est de faire ce que les autres disent que vous ne pouvez pas.",
    "N'y a-t-il pas autre chose sur laquelle vous devriez travailler maintenant?",
    "Ton père aime toujours et est toujours avec toi. Souviens-toi de ça.",
    "Avant de pouvoir renaître, vous devez mourir.",
    "Il vaut mieux être le marteau que le clou.",
    "Tout le monde vous admire pour votre talent et vos capacités.",
    "Sauvez les baleines. Collectionnez tout.",
    "Vous allez bientôt découvrir une vérité majeure sur celle que vous aimez le plus.",
    "Votre vie ne prospérera que si vous reconnaissez vos fautes et travaillez pour les réduire.",
    "Priez Dieu, mais ramez vers le rivage.",
    "Le lève-tôt attrape le ver, mais la deuxième souris récupère le fromage",
    "Au secours, je suis détenu dans une fabrique de biscuits chinoise.",
    "Hélas! L'oignon que vous mangez est le nénuphar de quelqu'un d'autre.",
    "Vous êtes un persoon avec un bon sens de la justice, maintenant il est temps d'agir comme ça.",
    "Vous créez de l'enthousiasme autour de vous.",
    "Il y a de grands changements à venir pour vous. Ils seront bons!",
    "Vous aurez bientôt beaucoup de jours heureux.",
    "De la confusion vient de nouveaux modèles.",
    "Si vous aimez assez quelqu'un et qu'il vous brise le cœur, vous ne pouvez pas vous empêcher de l'aimer encore, même après toute cette douleur.",
    "Regarde à droite ... Regarde à gauche ... Maintenant regarde en avant (fais-le très vite) est-ce que tu te sens différent? Bon, tu devrais avoir la tête qui tourne.",
    "Vivez comme si vous étiez au fond, même si vous êtes au sommet.",
    "Vous allez bientôt sortir victorieux du labyrinthe dans lequel vous avez voyagé.",
    "Ne jugez pas un livre par sa couleur.",
    "Tout viendra à votre façon.",
    "Il y a un temps pour être pratique maintenant.",
    "Pliez la tige tant qu'il est encore chaud.",
    "Les ténèbres ne réussissent que lorsqu'il n'y a pas de lumière. N'oubliez pas de lumière!",
    "Agir, ce n'est pas mentir. C'est trouver quelqu'un qui se cache à l'intérieur de vous et qui laisse cette personne courir librement.",
    "Vous serez obligé de faire face à la peur, mais si vous ne courez pas, la peur aura peur de vous.",
    "Vous envisagez de faire quelque chose. Ne le faites pas, cela n'aidera rien.",
    "Votre pire ennemi a le béguin pour vous!",
    "L'amour conquiert tout.",
    "La phrase est de suivre vos rêves. Pas une période de rêve.",
    "arrêtez de harceler votre partenaire et prenez-le au jour le jour.",
    "Ne pensez pas que mes frères ou moi avons le contrôle suprême sur ce qui va vous arriver.",
    "La malchance et le malheur vous suivront tous vos jours.",
    "Souviens-toi du destin du premier ver.",
    "Recommencez votre vie avec force, grâce et émerveillement",
    "Soyez un bon ami et un ennemi loyal.",
    "Plus ça change, plus c'est la même chose.",
    "La malchance et le malheur infesteront votre âme pathétique pour toute l'éternité.",
    "Le meilleur prophète du futur, c'est le passé",
    "Les films ont des boutons de pause, pas les amis",
    "Utilise la force.",
    "Faites confiance à votre intuition.",
    "Encouragez vos pairs.",
    "Laissez votre imagination vagabonder.",
    "Votre douleur est la rupture de la coquille qui enferme votre compréhension.",
    "La patience est la clé, une attente courte ou longue aura sa récompense.",
    "Dites-leur avant qu'il ne soit trop tard ...",
    "Un oiseau dans la main vaut trois dans la brousse !!",
    "Soyez ferme quand une action décisive est nécessaire.",
    "Pour déterminer si une personne est belle, ce n'est pas en regardant son apparence, mais son cœur.",
    "L'espoir apporte un meilleur avenir",
    "Pendant que vous avez ce jour, remplissez-le de vie. Pendant que vous êtes en ce moment, donnez-lui votre propre signification, votre but et votre joie.",
    "Même si cela sera souvent difficile et compliqué, vous savez que vous avez ce qu'il faut pour le faire.",
    "Vous pouvez choisir, maintenant et à tout moment, de mettre à profit vos capacités puissantes et efficaces. Vous pouvez toujours faire quelque chose, peu importe la situation, qui fera avancer votre vie.",
    "IL N'EST PAS BON D'UN UTILISATEUR. LES BÉNÉDICTIONS VIENNENT D'ÊTRE UN DON N'EST PAS UN PRENEUR.",
    "Cookie dit, tu me fais craquer",
    "Vous prospérerez dans le domaine des inventions farfelues.",
    "Votre langue est votre ambassadeur.",
    "Le remède contre le chagrin est le mouvement.",
    "L'amour est entre vos mains soyez heureux et tenez-vous-en.",
    "On vous demande souvent si c'est déjà arrivé",
    "La vie pour vous est une responsabilité audacieuse et fringante.",
    "La patience est la clé de la joie.",
    "Une affaire est quelque chose dont vous n'avez pas besoin à un prix auquel vous ne pouvez pas résister.",
    "Ce sera un jour catastrophique, préparez-vous!",
    "Restez à l'intérieur de vous-même, vous en bénéficierez de nombreuses façons.",
    "Il est rare qu'une grande beauté et une grande vertu habitent ensemble comme elles le sont en vous.",
    "Vous avez du talent à bien des égards.",
    "Vous êtes le maître de chaque situation.",
    "Votre problème est devenu encore plus grave. Réfléchissez, qu'avez-vous fait?",
    "Si votre biscuit est toujours en un seul morceau, achetez du loto.",
    "Suivre le courant rendra votre transition encore plus facile.",
    "Demain matin, tournez à gauche dès que vous quittez la maison",
    "Une métaphore pourrait vous sauver la vie.",
    "N'attendez pas que votre bateau entre, nagez jusqu'à lui",
    "Il y a des leçons à apprendre en écoutant les autres.",
    "Si vous voulez l'arc-en-ciel, vous devez tolérer la pluie.",
    "La Volition, la Force, les Langues, la Liberté et le Pouvoir reposent en vous.",
    "TROP DE PERSONNES VOLONTAIRES POUR PORTER LE TABOURD QUAND IL EST TEMPS DE DÉPLACER LE PIANO",
    "Il faut plus qu'un bon souvenir pour avoir de bons souvenirs.",
    "Vous êtes ce que vous êtes; comprenez-vous avant de réagir",
    "Parole aux sages: ne jouez pas à saute-mouton avec une licorne .........",
    "Pardonnez vos ennemis, mais ne les oubliez jamais.",
    "Tout va maintenant venir votre chemin",
    "Ne vous inquiétez pas pour le marché boursier. Investissez dans la famille.",
    "Il est beaucoup plus facile de rechercher le mauvais que de trouver le bon",
    "Si une personne qui vous a causé des souffrances et des souffrances vous a apporté, réexaminez la valeur de cette personne dans votre vie",
    "Tu vaux aimer, tu vaux aussi l'effort que cela prend pour t'aimer",
    "Ne cherchez pas les ennuis attendez qu'ils vous cherchent.",
    "Commencez par un nouveau départ - sortez de votre coquille.",
    "La vie est une piste de danse, vous êtes le DJ!",
    "Coopérer avec ceux qui ont à la fois le savoir-faire et l'intégrith.",
    "Les maux mineurs d’aujourd’hui porteront probablement leurs fruits demain.",
    "Vous êtes sur le point de devenir plus pauvre 8,95 $. (6,95 $ si vous aviez le buffet)",
    "Votre bouche bouge peut-être, mais personne n'écoute.",
    "Concentrez-vous sur la couleur jaune demain pour bonne chance!",
    "Le problème de la résistance à la tentation est qu’elle ne reviendra peut-être jamais.",
    "Toutes vos douleurs disparaîtront.",
    "Il était temps que je sois sorti de ce cookie.",
    "L'amour ouvrira la voie.",
    "La vengeance des annonces est un succès massif",
    "Il est préférable d'agir avec confiance, peu importe le peu de droit dont vous disposez.",
    "Bientôt, un visiteur vous ravira.",
    "Ce qui se brise dans un moment peut prendre des années à réparer.",
    "Quelqu'un a volé votre fortune et l'a remplacée par celle-ci. Votre chance est nulle. Passez une bonne journée!",
    "Prenez le contrôle de votre vie plutôt que de laisser les choses se passer comme ça!",
    "Vous serez récompensé pour votre patience et votre compréhension.",
    "Vous réaliserez tous vos désirs et plaisirs.",
    "Ne manquez jamais une occasion de garder votre bouche fermée.",
    "Rien ne montre le caractère d'un homme plus que ce qu'il rit.",
    "Ne regrette jamais quelque chose qui t'a fait sourire.",
    "L'Amour Pratique.",
    "Ne vous prenez pas au sérieux, personne d'autre ne le fait.",
    "Vous avez ce qu'il faut, mais il faudra tout ce que vous avez!",
    "En ce moment même, vous pouvez changer le reste de votre vie.",
    "Deviens qui tu es.",
    "Tout arrive au moment opportun pour celui qui sait attendre.",
    "L'énergie est en vous. L'argent vient!",
    "Les citations que vous ne comprenez pas, ne vous sont pas destinées.",
    "Vous avez un nouveau développement commercial important en préparation.",
    "si quelqu'un aime beaucoup le dire avant qu'il ne soit trop tard",
    "Les oiseaux sont empêtrés dans leurs pieds et les hommes dans leurs langues.",
    "Profitez en faisant des choses que les autres abandonnent.",
    "Le repos a un effet pacifique sur votre santé physique et émotionnelle.",
    "L’un des meilleurs moyens de persuader les autres est de l’écouter.",
    "Planifiez votre travail et travaillez votre plan.",
    "Plus de confiance en soi équivaut à être aveugle.",
    "Ceux qui ensoleillent la vie des autres ne peuvent le garder pour eux-mêmes",
    "Amour ou argent, ou ni?",
    "Avant le début d'un grand éclat, il doit y avoir du chaos.",
    "Les vieux amis font les meilleurs amis.",
    "Arrêtez de chercher pour toujours. Le bonheur est juste à côté de vous.",
    "Accepter quelque chose que vous ne pouvez pas changer et vous vous sentirez mieux.",
    "Le baiser n'est pas un baiser sans le coeur.",
    "Améliorez votre karma en vous engageant dans diverses activités caritatives.",
    "Vous aurez de la chance et surmonterez de nombreuses difficultés.",
    "On n'hésite jamais à s'attaquer aux problèmes les plus difficiles.",
    "L'espoir est comme la nourriture. Vous mourrez de faim sans elle.",
    "QUAND LE FEU ET L'EAU RENDENT À L'EAU DE GUERRE TOUJOURS GAGNE.",
    "Un homme en colère ouvre la bouche et ferme les yeux.",
    "Faites en sorte que le système fonctionne pour vous et non l'inverse.",
    "Vous aurez bientôt faim, commande à emporter maintenant.",
    "Soyez prêt pour plus d'énergie.",
    "Une relation inattendue deviendra permanente.",
    "L'amour de votre vie est assis en face de vous.",
    "Mieux vaut être la tête d'un poulet que la queue d'un boeuf.",
    "Pardonner aux autres une fois de plus, c'est créer une bénédiction supplémentaire pour vous-même.",
    "Amusez-vous pendant que vous le pouvez.",
    "Le test ultime d'une relation est de ne pas être d'accord mais de se tenir la main.",
    "L’excellence fait la différence entre ce que je fais et ce dont je suis capable.",
    "Ne laissez pas ce que vous n'avez pas vous empêcher d’utiliser ce que vous avez.",
    "Ce qui finit sur l'espoir ne finit pas du tout.",
    "Les gens aiment vous avoir. Appréciez cela.",
    "Vous êtes admiré pour vos manières aventureuses.",
    "Il n'y a jamais trop de monde le long du petit kilomètre",
    "Vous êtes bénis, aujourd'hui est le jour pour bénir les autres.",
    "La plus grande guerre n’est parfois pas sur le champ de bataille, mais contre soi-même.",
    "Les gens de votre entourage seront plus coopératifs que d'habitude.",
    "Un bon moyen de rester en bonne santé est de manger plus de nourriture chinoise.",
    "Quiconque ose être, ne peut jamais être faible.",
    "Affirmez-le, visualisez-le, croyez-le et il s’actualisera lui-même.",
    "La mesure du temps à votre prochain objectif est la mesure de votre discipline.",
    "Au secours, je suis prisonnier dans une boulangerie chinoise !!!",
    "Prenez une minute et laissez-le rouler, puis prenez une minute pour le laisser respirer.",
    "Nous sommes ici pour nous aimer, nous servir et nous élever les uns les autres.",
    "Si tout le monde est un ver, vous devriez être un ver luisant",
    "Affirmer, c'est rendre ferme.",
    "Souvenez-vous de ceci: le ruban adhésif peut tout réparer, alors ne vous inquiétez pas.",
    "Vous avez cassé mon cookie!",
    "Un échec n’est pas une défaite tant que vous n’arrêtez pas d’essayer.",
    "Les jours qui nous rendent heureux nous rendent sages.",
    "Les hommes ne manquent pas ... ils renoncent à essayer.",
    "Le temps passe vite. Mais pas les souvenirs.",
    "Vous allez réussir dans tout ce que vous adoptez",
    "Vous allez distancer tous vos concurrents.",
    "Vous avez une grande capacité pour casser les cookies - utilisez-le à bon escient!",
    "Parfois, il est préférable de savoir quand sortir que d'entrer",
    "L'argent viendra à vous quand vous faites la bonne chose.",
    "Quand vous obtenez quelque chose pour rien, vous n'avez pas encore été facturé pour cela.",
    "Vous découvrirez vos talents cachés.",
    "Vous allez avancer avec vos capacités.",
    "Lorsque vous ne pouvez pas vous sentir naturellement optimiste, cela peut parfois vous aider à agir comme si vous l'aviez fait.",
    "Vous surmonterez des moments difficiles.",
    "Votre problème vient de devenir votre tremplin. Saisissez le moment.",
    "Je suis une fortune. Vous venez de casser ma petite maison. Où vais-je vivre maintenant?",
    "La majorité du mot ne peut pas est peut.",
    "Le secret pour avancer est de commencer.",
    "Soyez très affectueux aujourd'hui.",
    "Changez vos pensées et vous changez le monde.",
    "Chante et réjouis-toi, la fortune te sourit.",
    "Toute la préparation que vous avez faite sera finalement payante!",
    "Une personne vraiment formidable n'abandonne jamais la simplicité d'un enfant.",
    "Le service client, c'est comme prendre un bain, il faut continuer à le faire.",
    "L'étendue de votre intelligence est un vide qu'aucun univers ne pourrait jamais combler.",
    "Ces raisins que vous ne pouvez pas goûter sont toujours acides.",
    "Une connaissance inattendue va refaire surface.",
    "Si vous voulez l'arc-en-ciel, alors vous devez tolérer la pluie.",
    "Vous n'obtenez pas d'harmonie quand tout le monde chante la même note.",
    "La course n’est pas toujours rapide, mais à ceux qui continuent à courir.",
    "Le lève-tôt attrape le ver, mais la deuxième souris récupère le fromage.",
    "Les meilleures choses de la vie ne sont pas des choses.",
    "Ne cherchez pas à trouver la faute. La récompense de la trouver est faible.",
    "Tout a une beauté mais tout le monde ne la voit pas.",
    "Rien n'est aussi bon ou mauvais qu'il n'y parait.",
    "Ne coupe jamais ce que tu peux dénouer.",
    "Rencontrez votre adversaire à mi-chemin. Vous avez besoin de l'exercice.",
    "Le rire est la distance la plus courte entre deux personnes.",
    "Nous ne pouvons pas changer la direction du vent, mais nous pouvons régler nos voiles.",
    "Nous pourrions apprendre beaucoup des crayons: certains sont tranchants, d'autres jolies, d'autres portent des noms étranges, et tous sont de couleurs différentes. Mais ils doivent tous apprendre à vivre dans la même boîte.",
    "Utilisez votre instinct maintenant.",
    "Si vous faites un pas dans votre chemin, vous réussirez; il est préférable d’échouer.",
    "Aux yeux des amoureux, tout est beau.",
    "Attention, ne mangez pas votre fortune.",
    "Faites preuve de raffinement dans tout ce que vous faites.",
    "Les normes impossibles rendent la vie difficile.",
    "Un monde différent ne peut pas être construit par des personnes indifférentes.",
    "Tous les problèmes que vous avez peuvent disparaître très rapidement.",
    "L'intégrité est l'essence de tout ce qui réussit.",
    "Pour l'amour vrai? Envoyez de vraies roses conservées en or 24 carats!",
    "Parfois, l'objet du voyage n'est pas la fin, mais le voyage lui-même.",
    "La peur est juste une excitation qui nécessite un ajustement de son attitude.",
    "La nourriture ici est si bonne, même un homme des cavernes aime ça.",
    "Peut-être que vous êtes trop concentré sur les dépenses.",
    "Le bonheur n'est pas quelque chose dont vous vous souvenez, c'est quelque chose que vous expérimentez.",
    "Oups ... Mauvais cookie.",
    "Le rêve est en vous.",
    "L'amour est en route.",
    "Soyez direct, généralement on peut accomplir plus de cette façon.",
    "Utilisez vos talents. C'est ce à quoi ils sont destinés.",
    "Les problèmes que vous avez maintenant disparaîtront rapidement.",
    "Voir la lumière au bout du tunnel.",
    "Ne faites pas face à la réalité, que ce soit l'endroit d'où vous sautez.",
    "La fortune vous sourit aujourd'hui.",
    "Croire, c'est faire.",
    "Vos yeux dynamiques ont attiré un admirateur secret.",
    "Vous savez où vous allez et comment vous y rendre.",
    "Suivez vos rêves avec assurance.",
    "Votre capacité à choisir un gagnant vous apportera le succès.",
    "L’humour fonctionne habituellement au moment de la maladresse.",
    "Un bon moment pour finir de vieilles tâches.",
    "Arrêtez de procrastiner - à partir de demain",
    "Un leadership enthousiaste vous procure une promotion quand vous vous y attendez le moins.",
    "Vous aimez la nourriture chinoise.",
    "Vous êtes beaucoup plus influent que vous ne le pensez.",
    "Ajustez vos finances, établissez des budgets, pour améliorer votre réputation.",
    "Le bonheur n'est pas l'absence de conflit, mais la capacité de le gérer.",
    "Un cœur compréhensif réchauffe tout ce qui est doté de sa présence.",
    "Vos collègues apprécient votre grande créativité.",
    "Vous êtes l'une des personnes qui va dans la vie.",
    "Les autres apprécient votre compagnie.",
    "En cas de doute, laissez votre instinct vous guider.",
    "Un message joyeux vous est destiné.",
    "Une bonne surprise vous attend ce soir.",
    "vous ne pouvez pas descendre le bon chemin sans avoir tout d'abord découvert le chemin à suivre",
    "Assumer courageusement la responsabilité de son erreur est un caractère.",
    "La joyeuse énergie du jour aura un effet positif sur vous.",
    "Vous avez un fort désir de maison et vos intérêts familiaux passent en premier.",
    "Les chiens ont des propriétaires, les chats ont du personnel.",
    "Soyez patient: avec le temps, même un œuf marchera.",
    "Vous n'êtes pas une personne qui peut être ignorée.",
    "Vous savez toujours le bon moment pour vous affirmer ou simplement attendre.",
    "Lire dans l'esprit est ce que l'exercice représente pour le corps.",
    "Mange quelque chose que tu n'as jamais essayé auparavant.",
    "Votre vie devient de plus en plus une aventure!",
    "Vous devez vivre authentiquement, et vous ne pouvez pas l'ignorer.",
    "Faites tout ce que vous pouvez, sauvez tout ce que vous pouvez, donnez tout ce que vous pouvez.",
    "Une lance bien dirigée vaut trois.",
    "Pour construire un monde meilleur, commencez dans votre communauté.",
    "Lorsque vous ne pouvez pas vous sentir naturellement optimiste, il peut parfois être utile d'agir si vous le faisiez.",
    "Puissiez-vous avoir de la chance.",
    "Un mot gentil tiendra quelqu'un au chaud pendant des années.",
    "Rien au monde n'est accompli sans passion.",
    "Langage inventé par l'homme pour satisfaire le besoin de se plaindre.",
    "Acceptez ce qui vous arrive chaque jour.",
    "Un petit paquet chanceux est en route pour vous bientôt.",
    "Dans les entreprises humaines, le hasard favorise les esprits préparés.",
    "Ne contrariez pas le pingouin aujourd'hui.",
    "Ne pleure pas.",
    "La meilleure façon de donner du crédit est de le donner.",
    "Tout ce que vous faites, faites-le bien. La dernière chose que vous voulez, c'est être désolé pour ce que vous n'avez pas fait.",
    "Il faut plus que de la bonne mémoire pour avoir de bons souvenirs.",
    "Accorde-toi un voeu cette année seulement, tu peux le faire.",
    "aime ton prochain, ne te fais pas attraper",
    "Vous serez sélectionné pour une promotion en raison de vos réalisations.",
    "Il y a beaucoup de nouvelles opportunités qui vous sont présentées.",
    "Vous allez hériter d'une grosse somme d'argent.",
    "Vous recevrez un cadeau de quelqu'un qui se soucie de vous.",
    "Vous n'êtes pas analphabète.",
    "Amour parce que c'est la seule vraie aventure.",
    "Vous envisagez une action qui vous apportera du crédit",
    "Restez fidèle aux rêves de votre jeunesse.",
    "Chérissez ce que vous avez.",
    "Le plus grand précepte est la conscience continue.",
    "Un nouvel ami vous aide à sortir d'une vieille routine.",
    "J'ai un rêve ... Il est temps d'aller se coucher.",
    "Votre habileté accomplira ce que la force de beaucoup ne peut pas.",
    "Vous serez bientôt entourés de bons amis et de rires.",
    "Il vaut mieux être le marteau que l'enclume.",
    "Celui qui monte une échelle doit commencer par le premier pas.",
    "L'action ne dit rien, sans le motif.",
    "Donnez-vous un peu de paix et de calme pendant au moins quelques heures.",
    "Vivre chaque jour bien et sagement",
    "Les vieux rêves ne meurent jamais, ils sont simplement classés.",
    "Vous pouvez y remédier avec un peu d'énergie supplémentaire et une attitude positive.",
    "La vie est un verbe",
    "Un homme sans but est comme une horloge sans aiguilles, aussi inutile si elle tourne comme si elle se tenait debout.",
    "Beaucoup de gens sont à peu près aussi heureux qu'ils se décident.",
    "C'est assez amusant de faire l'impossible",
    "Wow! Un message secret de vos dents!",
    "Vous devriez être capable de gagner de l'argent et de le conserver.",
    "L'esprit humain est plus fort que tout ce qui peut lui arriver.",
    "Votre succès étonnera tout le monde.",
    "Il vaut mieux avoir une poule demain qu'un oeuf aujourd'hui.",
    "Jugez chaque jour non par la récolte que vous récoltez, mais par les graines que vous plantez.",
    "Vous aimez la cuisine chinoise.",
    "Votre travail acharné portera ses fruits aujourd'hui.",
    "Aujourd'hui, c'est demain que nous nous sommes inquiétés pour hier",
    "Il n'y a pas de raccourcis pour les endroits qui valent le coup",
    "Peu importe votre passé, vous avez un avenir sans tache.",
    "Votre désir secret de changer complètement votre vie se manifestera.",
    "Bientôt, vous serez assis au sommet du monde.",
    "Vous n'êtes jamais égoïste avec vos conseils ou votre aide.",
    "Un temps passionnant vous est réservé.",
    "C'est dur d'être fascinant.",
    "Bientôt la vie deviendra plus intéressante",
    "La chance rend parfois visite à un imbécile, mais il ne s'assied jamais avec lui.",
    "Gardez vos plans secrets pour l'instant.",
    "N'es-tu pas content que tu aies juste pris un bon repas?",
    "Voyager cette année mettra votre vie en perspective.",
    "Seules les personnes talentueuses obtiennent l'aide des autres.",
    "Un broyage constant peut transformer un signe de fer en aiguille.",
    "Vous aurez du succès dans votre travail",
    "vous passerez la vieillesse dans le confort et la richesse matérielle",
    "Quand vous allez transformer votre coeur en pierre, souvenez-vous: vous ne marchez pas seul.",
    "Je suis une personne malchanceuse depuis ma naissance",
    "Vous êtes vigoureux dans les mots et l'action.",
    "Celui qui ronfle s'endormira toujours le premier.",
    "Un extraterrestre vous apparaîtra sous peu!",
    "Le repos est une bonne chose, mais l'ennui est son frère.",
    "Ne jugez pas excessivement les intentions ou les actions de votre bien-aimé",
    "Pensez à comment vous pouvez aider sur un problème, pas à qui blâmer.",
    "La vie de chaque femme ou homme - son coeur - est une joie pure et sainte.",
    "Relax",
    "Faites confiance à votre intuition. L'univers guide votre vie.",
    "Utilise ta tête, mais vis dans ton coeur.",
    "Ne trouve pas à redire, trouve un remède",
    "Ce sont peut-être ceux qui font le plus, qui rêvent le plus",
    "Vos passions vous emportent.",
    "Écoutez-vous plus souvent",
    "Pensez davantage aux exhortations de la mère.",
    "Le joueur est comme le pêcheur a la chance débutants.",
    "Vous avez la chance de prendre part à une aventure passionnante.",
    "La réponse la plus simple est d'agir.",
    "Vous serez toujours entouré de vrais amis.",
    "Gardez les pieds sur terre même si des amis vous flatteront",
    "Vous êtes l'homme de justice et d'intégrité.",
    "Celui qui cherche trouvera.",
    "La chose intelligente à faire est de commencer à faire confiance à vos intuitions.",
    "Vos nombreux talents cachés deviendront évidents pour ceux qui vous entourent.",
    "Choisissez un chemin avec le coeur.",
    "L'esprit humain est plus fort que tout ce qui peut lui arriver.",
    "Il faut plus que de la bonne mémoire pour avoir de bons souvenirs.",
    "Faire face aux faits avec dignité.",
    "Soyez calme face à une crise d'urgence.",
    "Une nouvelle garde-robe apporte une grande joie et un changement dans votre vie.",
    "Tout le monde convient que vous êtes le meilleur.",
    "Une nouvelle perspective illumine votre image et apporte de nouveaux amis.",
    "Tout va maintenant venir votre chemin.",
    "Vous serez appelé à occuper un poste de grand honneur et de grande responsabilité.",
    "Les yeux se croient; les oreilles croient les autres.",
    "Le bon début est à moitié fait.",
    "Certains poursuivent le bonheur; vous le créez.",
    "C'est le pire des cas, vous devez faire appel à votre optimisme.",
    "Vous êtes prudent en montrant votre vrai soi aux autres.",
    "Votre capacité à accomplir des tâches suivra avec succès.",
    "Nous avons tous un code extraordinaire en nous, qui attend d'être publié.",
    "Vous aurez un avenir radieux.",
    "La compassion est une façon d'être.",
    "Vous aurez toujours de la chance dans vos affaires personnelles.",
    "Le plaisir de ce que nous apprécions est perdu en voulant plus",
    "Vous êtes-vous souvenu de commander votre emporter aussi?",
    "Peut-être que vous vous concentrez trop sur cette seule chose ..",
    "En ce moment, une énergie vous pousse dans une nouvelle direction.",
    "Tout le monde se sent chanceux de vous avoir comme ami.",
    "Quand le moment viendra, prenez le premier.",
    "Parfois, voyager dans de nouveaux endroits entraîne de grandes transformations.",
    "Il y a toujours un moyen - si vous êtes commis.",
    "La vie est trop courte pour perdre du temps à haïr quelqu'un.",
    "Le monde entier n’aimera peut-être pas un amant, mais ils le surveilleront.",
    "Ne perdez pas votre temps, investissez-le.",
    "La vie devient toujours plus difficile près du sommet.",
    "Prenez la chance pendant que vous avez encore le choix.",
    "Il est beaucoup plus facile d'être cirtique que d'être correct.",
    "Profitez de la vie! Mieux vaut être heureux que sage.",
    "Pour faire avancer le chariot, il faut graisser les roues.",
    "Vous envisagez une action qui vous apportera un crédit.",
    "Avant de vous demander, est-ce que je fais bien les choses, demandez, est-ce que je fais les bonnes choses?",
    "Vous pouvez être déçu si vous échouez, mais vous êtes condamné si vous n'essayez pas.",
    "Vous obtiendrez toujours ce que vous voulez grâce à votre charme et à votre personnalité.",
    "Les grands problèmes sont le travail, la carrière ou le statut actuel.",
    "Vos courants émotionnels coulent puissamment maintenant.",
    "Toute décision que vous devez prendre demain est une bonne décision.",
    "Consommez moins. Partagez plus. Profitez de la vie.",
    "Le secret pour rester jeune est de rester en bonne santé et de mentir à propos de son âge.",
    "Le printemps est arrivé. La vie s'épanouit.",
    "Va demander à ta mère.",
    "La possibilité d'un changement de carrière est proche.",
    "L'important est de ne jamais cesser de poser des questions.",
    "La compassion guérira plus que la condamnation.",
    "Les excuses sont faciles à fabriquer et difficiles à vendre.",
    "Mettez votre esprit dans la planification aujourd'hui. Regardez dans le futur.",
    "Écoutez la vie et vous entendrez la voix de la vie pleurer, soyez!",
    "Broke est seulement temporaire, pauvre est un état d’esprit.",
    "Le travail d'équipe: le carburant qui permet aux gens du commun d'obtenir des résultats peu communs.",
    "Les mots durs ne cassent pas les os, les beaux mots beurre pas de panais.",
    "Nous ne pouvons pas diriger le vent mais nous pouvons régler les voiles.",
    "On vous offre le rêve d'une vie. Dites oui!",
    "S'attaquer aux problèmes d'aujourd'hui contribuera à un avenir meilleur.",
    "Vous avez un sourire curieux et une nature mystérieuse.",
    "Les questions fournissent la clé pour libérer notre potentiel illimité.",
    "Vous bénéficierez aujourd'hui d'une vision spirituelle d'une netteté remarquable.",
    "Les sages sont conscients de leur trésor, tandis que les imbéciles suivent leur vanité",
    "Un temps bien organisé est le signe le plus sûr d'un esprit bien organisé.",
    "N'apportez jamais de sentiments malheureux chez vous.",
    "C'est vraiment une belle journée. Félicitations!",
    "La malchance et le malheur vont infester votre âme pathétique pour toute l'éternité.",
    "Un oeuf d'or d'opportunité tombe sur vos genoux ce mois-ci.",
    "Vous êtes très reconnaissant pour les petits plaisirs de la vie.",
    "Aujourd'hui, vous devriez être un passager. Restez près du conducteur pendant un jour.",
    "Car la haine n'est jamais vaincue par la haine. La haine est vaincue par l'amour.",
    "Le service est le loyer que nous payons pour le privilège de vivre sur cette planète.",
    "Les bons vêtements ouvrent beaucoup de portes. Allez faire les magasins.",
    "Le leader cherche à communiquer sa vision à ses disciples.",
    "Les grands travaux sont accomplis non par la force, mais par la persévérance.",
    "Les personnes en retard sont souvent plus heureuses que celles qui doivent les attendre",
    "Présentez vos meilleures idées aujourd'hui à un public enthousiaste et accueillant.",
    "Des amis longtemps absents vous reviennent.",
    "Le moment est venu de se faire de nouveaux amis.",
    "La vie est pour vous une aventure fringante et audacieuse",
    "Vous aurez peut-être bientôt faim: commandez un plat à emporter maintenant",
    "N'hésitez pas à chercher de l'aide, une main supplémentaire devrait toujours être la bienvenue.",
    "Comment pouvez-vous avoir une belle fin sans faire de belles erreurs?",
    "L'humour est une affirmation de dignité",
    "Celui qui monte une échelle doit commencer par le premier pas",
    "Quel est le vice aujourd'hui peut être la vertu de demain.",
    "Vous avez une personnalité inhabituellement magnétique.",
    "Vous allez voyager dans de nombreux endroits.",
    "Acceptez-vous",
];
exports.data = data;